# Generated by Django 2.2.3 on 2019-08-05 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shopApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='shopingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('itemName', models.CharField(max_length=40)),
                ('itemSize', models.CharField(max_length=5)),
                ('itemImg', models.ImageField(height_field=400, upload_to=shopApp.models.create_filename, width_field=700)),
                ('discription', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
