# Generated by Django 2.2.3 on 2019-08-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopingitem',
            name='itemImg',
            field=models.ImageField(height_field=400, upload_to='item/', width_field=700),
        ),
    ]
