# Generated by Django 2.2.3 on 2019-08-05 09:25

from django.db import migrations, models
import shopApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0002_auto_20190805_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopingitem',
            name='itemImg',
            field=models.ImageField(height_field='400', upload_to=shopApp.models.create_filename, width_field='700'),
        ),
    ]
