# Generated by Django 2.2.3 on 2019-08-05 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shopApp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopApp', '0004_auto_20190805_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=40)),
                ('itemSize', models.CharField(max_length=5)),
                ('itemImg', models.ImageField(upload_to=shopApp.models.create_filename)),
                ('discription', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='userProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopApp.products')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='shopingItem',
        ),
    ]
