# Generated by Django 2.2.3 on 2019-08-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0005_auto_20190805_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='itemSize',
            field=models.CharField(choices=[('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=5),
        ),
    ]
